## Assignment by Kan Innovations

#### Problem Statement:
The excel file contains images of two feet or rather high values in a pattern that represent a foot. What you need to do is extract the positions and the values of the edges of the feet. You can do this by assuming both the feet as one image and extract the left and right edges of the entire image or you can isolate each foot and extract their edges individually.

#### Importing important libraries

In [ ]:
import openpyxl 
import pandas as pd

#### Operations

In [ ]:
# Give the location of the file 
path = r'C:\Users\YASHA\Desktop\Assignment01_1\Assignment01\img.xlsx'
  
# workbook object is created 
wb_obj = openpyxl.load_workbook(path) 

# worksheet object is created
sheet_obj = wb_obj.active

#### For Left feet

In [202]:
# lists for appending Final values
rows = []
columns = []
position = []

# looping for structure
for j in range(6, 29): # j represents rows
    for i in range(3,20): # i represents columns
        cell_obj = sheet_obj.cell(row = j,column = i)
        cell_obj_lft = sheet_obj.cell(row = j,column = i - 1)
        cell_obj_rt = sheet_obj.cell(row = j,column = i + 1)
        if ((cell_obj.value is not None) & (cell_obj_lft.value is None)) or ((cell_obj.value is not None) & (cell_obj_rt.value is None)):
            rows.append(cell_obj.row)
            columns.append(cell_obj.column)
            position.append(cell_obj.value)
                        
# initialize list of lists 
data = [rows, columns, position] 
  
# Create the pandas DataFrame 
Left_feet = pd.DataFrame(data, index  =['lft_rows', 'lft_columns','lft_position']) 
  
# print dataframe. 
Left_feet.T

    lft_rows  lft_columns  lft_position
0          6           14             7
1          6           16            10
2          7           13            15
3          7           17             5
4          8           12             3
5          8           17            16
6          9           12             9
7          9           18             3
8         10           12            22
9         10           18             8
10        11           12            24
11        11           17             4
12        12           11             4
13        12           16            18
14        13           11             4
15        13           15             4
16        14           10             8
17        14           14            11
18        15           10            14
19        15           13            12
20        16           10            10
21        16           12            11
22        17            9             3
23        17           12            10
24        18            9             5
25        18           10             8
26        19            9             7
27        19           10             3
28        20            8             5
29        20           10            11
30        20           12             6
31        21            8            33
32        21           15             2
33        22            8            13
34        22           16             2
35        23            9            21
36        23           15             4
37        24            9             3
38        24           12            15
39        24           14             3
40        25           10             4
41        25           12             5
42        26           10             6
43        27            8             6
44        27           11             6
45        27           12            10
46        27           14             8
47        28           11             4
48        28           14             3

#### For right feet

In [203]:
# lists for appending Final values
rows = []
columns = []
position = []

# looping for structure
for j in range(6, 29): # j represents rows
    for i in range(21,35): # i represents columns
        cell_obj = sheet_obj.cell(row = j,column = i)
        cell_obj_lft = sheet_obj.cell(row = j,column = i - 1)
        cell_obj_rt = sheet_obj.cell(row = j,column = i + 1)
        if ((cell_obj.value is not None) & (cell_obj_lft.value is None)) or ((cell_obj.value is not None) & (cell_obj_rt.value is None)):
            rows.append(cell_obj.row)
            columns.append(cell_obj.column)
            position.append(cell_obj.value)
                        
# initialize list of lists 
data = [rows, columns, position] 
  
# Create the pandas DataFrame 
Right_feet = pd.DataFrame(data, index  =['rt_rows', 'rt_columns','rt_position']) 
  
# print dataframe. 
Right_feet.T

    rt_rows  rt_columns  rt_position
0         6          26            5
1         6          29            5
2         7          25            8
3         7          30            6
4         8          25           23
5         8          30           17
6         9          25           47
7         9          30           19
8        10          25           35
9        10          30           24
10       11          25           14
11       11          31            4
12       12          26           15
13       12          31            8
14       13          28           10
15       13          31           10
16       14          28           12
17       14          32            4
18       15          28            6
19       15          32           14
20       16          28            3
21       16          32           10
22       17          29            7
23       17          32           15
24       18          29            8
25       18          32           10
26       19          30           24
27       19          32           17
28       20          27            7
29       20          33           17
30       21          28            4
31       21          34            3
32       22          26            3
33       22          34            4
34       23          26            4
35       23          34            3
36       24          26           11
37       24          33            4
38       25          26            5
39       25          32            4
40       26          29            5
41       26          31            4
42       27          26           23
43       27          32            5
44       27          33            5
45       28          26            3

#### For Both

In [204]:
# lists for appending Final values
rows = []
columns = []
position = []

# looping for structure
for j in range(6, 29): # j represents rows
    for i in range(3,36): # i represents columns
        cell_obj = sheet_obj.cell(row = j,column = i)
        cell_obj_lft = sheet_obj.cell(row = j,column = i - 1)
        cell_obj_rt = sheet_obj.cell(row = j,column = i + 1)
        if ((cell_obj.value is not None) & (cell_obj_lft.value is None)) or ((cell_obj.value is not None) & (cell_obj_rt.value is None)):
            rows.append(cell_obj.row)
            columns.append(cell_obj.column)
            position.append(cell_obj.value)
                        
# initialize list of lists 
data = [rows, columns, position] 
  
# Create the pandas DataFrame 
Both_feet = pd.DataFrame(data, index  =['Both_rows', 'Both_columns','Both_position']) 
  
# print dataframe. 
Both_feet.T

    Both_rows  Both_columns  Both_position
0           6            14              7
1           6            16             10
2           6            26              5
3           6            29              5
4           7            13             15
5           7            17              5
6           7            25              8
7           7            30              6
8           8            12              3
9           8            17             16
10          8            25             23
11          8            30             17
12          9            12              9
13          9            18              3
14          9            25             47
15          9            30             19
16         10            12             22
17         10            18              8
18         10            25             35
19         10            30             24
20         11            12             24
21         11            17              4
22         11            25             14
23         11            31              4
24         12            11              4
25         12            16             18
26         12            26             15
27         12            31              8
28         13            11              4
29         13            15              4
..        ...           ...            ...
65         22             8             13
66         22            16              2
67         22            26              3
68         22            34              4
69         23             9             21
70         23            15              4
71         23            26              4
72         23            34              3
73         24             9              3
74         24            12             15
75         24            14              3
76         24            26             11
77         24            33              4
78         25            10              4
79         25            12              5
80         25            26              5
81         25            32              4
82         26            10              6
83         26            29              5
84         26            31              4
85         27             8              6
86         27            11              6
87         27            12             10
88         27            14              8
89         27            26             23
90         27            32              5
91         27            33              5
92         28            11              4
93         28            14              3
94         28            26              3

[95 rows x 3 columns]

#### Explanation:
I have created a Data Frame so that, output can be seen properly.

I have checked the condition of the present cell with previous cell and next cell, if present cell value is not none and previous cell is none then take that cell value and other condition if present cell value is not none and next cell is none then also take that cell.

##### Note:
Their is a scope for improvement in the code, I can add few more and better this to this code.